.PHONY: help
help:
	@echo "Build targets:"
	@echo ""
	@echo "    all          Equivalent to 'teco' target."
	@echo "    clean        Clean object files and executables."
	@echo "    distclean    Clean everything."
	@echo "    doc          Create or update documentation (requires Doxygen)."
	@echo "    help         Print this message."
	@echo "    install      Build executable and copy to /usr/local/bin."
	@echo "    mostlyclean  Clean object files."
	@echo "    teco         Build TECO-64 text editor. [default]"
	@echo ""
	@echo "Build options:"
	@echo ""
	@echo "    buffer=gap   Use gap buffer for editing text. [default]"
	@echo "    display=on   Enable display mode. [default]"
	@echo "    display=off  Enable display mode."
	@echo "    headers      Rebuild header files if needed."
	@echo "    int=32       Use 32-bit integers. [default]."
	@echo "    int=64       Use 64-bit integers."
	@echo "    paging=std   Use standard paging."
	@echo "    paging=vm    Use virtual memory paging. [default]"
	@echo ""
	@echo "Debugging options:"
	@echo ""
	@echo "    lint         Lint .c and .lob files (requires PC-lint)."
	@echo "    lobs         Lint .c files (requires PC-lint)."
	@echo "    gdb=1        Enable use of GDB debugger."
	@echo "    gprof=1      Enable use of GPROF profiler."
	@echo "    memcheck=1   Enable checks for memory leaks."
	@echo "    verbose=1    Enable verbosity during build."
	@echo ""
	@echo "Optimization options:"
	@echo ""
	@echo "    ndebug=1     Disable run-time assertions."
	@echo "    nostrict=1   Disable run-time syntax checking."
	@echo ""
