#
#  Define TECO source files. The first set include general purpose functions,
#  and the second set include functions used for specific commands.
#

SOURCES = \
    build_str.c    \
    cmd_buf.c      \
    cmd_estack.c   \
    cmd_exec.c     \
    cmd_scan.c     \
    env_sys.c      \
    errors.c       \
    file.c         \
    file_sys.c     \
    memory.c       \
    option_sys.c   \
    qreg.c         \
    search.c       \
    teco.c         \
    term_buf.c     \
    term_in.c      \
    term_out.c     \
    term_rubout.c  \
    term_sys.c     \
                   \
    a_cmd.c        \
    bracket_cmd.c  \
    case_cmd.c     \
    ctrl_a_cmd.c   \
    ctrl_t_cmd.c   \
    ctrl_u_cmd.c   \
    ctrl_v_cmd.c   \
    ctrl_w_cmd.c   \
    datetime_cmd.c \
    delete_cmd.c   \
    ea_cmd.c       \
    eb_cmd.c       \
    ec_cmd.c       \
    ef_cmd.c       \
    eg_cmd.c       \
    ei_cmd.c       \
    ek_cmd.c       \
    el_cmd.c       \
    em_cmd.c       \
    en_cmd.c       \
    eo_cmd.c       \
    ep_cmd.c       \
    e_pct_cmd.c    \
    eq_cmd.c       \
    equals_cmd.c   \
    er_cmd.c       \
    esc_cmd.c      \
    e_ubar_cmd.c   \
    ew_cmd.c       \
    ex_cmd.c       \
    ez_cmd.c       \
    fb_cmd.c       \
    fd_cmd.c       \
    ff_cmd.c       \
    fk_cmd.c       \
    flag_cmd.c     \
    fr_cmd.c       \
    g_cmd.c        \
    goto_cmd.c     \
    if_cmd.c       \
    insert_cmd.c   \
    loop_cmd.c     \
    m_cmd.c        \
    move_cmd.c     \
    n_cmd.c        \
    number_cmd.c   \
    oper_cmd.c     \
    p_cmd.c        \
    pct_cmd.c      \
    q_cmd.c        \
    radix_cmd.c    \
    s_cmd.c        \
    trace_cmd.c    \
    type_cmd.c     \
    ubar_cmd.c     \
    u_cmd.c        \
    var_cmd.c      \
    w_cmd.c        \
    x_cmd.c        \
    yank_cmd.c     \
