#!/bin/sh
#grep exec_A src/*.c
#grep exec_C src/*.c
#grep exec_D src/*.c
#grep exec_G src/*.c
#grep exec_I src/*.c
#grep exec_J src/*.c
#grep exec_K src/*.c
#grep exec_L src/*.c
#grep exec_M src/*.c
#grep exec_N src/*.c
#grep exec_O src/*.c
#grep exec_P src/*.c
#grep exec_Q src/*.c
#grep exec_R src/*.c
#grep exec_S src/*.c
#grep exec_T src/*.c
#grep exec_U src/*.c
#grep exec_V src/*.c
#grep exec_W src/*.c
#grep exec_X src/*.c
#grep exec_Y src/*.c
#grep exec_Z src/*.c
#grep exec_apos src/*.c
#grep exec_bslash src/*.c
#grep exec_bang src/*.c
#grep exec_ctrl_a src/*.c
#grep exec_ctrl_c src/*.c
#grep exec_ctrl_d src/*.c
#grep exec_ctrl_e src/*.c
#grep exec_ctrl_f src/*.c
#grep exec_ctrl_i src/*.c
#grep exec_ctrl_l src/*.c
#grep exec_ctrl_o src/*.c
#grep exec_ctrl_p src/*.c
#grep exec_ctrl_q src/*.c
#grep exec_ctrl_r src/*.c
#grep exec_ctrl_s src/*.c
#grep exec_ctrl_t src/*.c
#grep exec_ctrl_u src/*.c
#grep exec_ctrl_ubar src/*.c
#grep exec_ctrl_v src/*.c
#grep exec_ctrl_w src/*.c
#grep exec_ctrl_x src/*.c
#grep exec_equals src/*.c
#grep exec_escape src/*.c
#grep exec_langle src/*.c
#grep exec_lbracket src/*.c
#grep exec_pct src/*.c
#grep exec_question src/*.c
#grep exec_quote src/*.c
#grep exec_rangle src/*.c
#grep exec_rbracket src/*.c
#grep exec_rparen src/*.c
#grep exec_semi src/*.c
#grep exec_ubar src/*.c
#grep exec_vbar src/*.c
#grep exec_EA src/*.c
#grep exec_EB src/*.c
#grep exec_EC src/*.c
#grep exec_ED src/*.c
#grep exec_EE src/*.c
#grep exec_EF src/*.c
#grep exec_EG src/*.c
#grep exec_EH src/*.c
#grep exec_EI src/*.c
#grep exec_EJ src/*.c
#grep exec_EK src/*.c
#grep exec_EL src/*.c
#grep exec_EM src/*.c
#grep exec_EN src/*.c
#grep exec_EO src/*.c
#grep exec_EP src/*.c
#grep exec_EQ src/*.c
#grep exec_ER src/*.c
#grep exec_ES src/*.c
#grep exec_ET src/*.c
#grep exec_EU src/*.c
#grep exec_EV src/*.c
#grep exec_EW src/*.c
#grep exec_EX src/*.c
#grep exec_EY src/*.c
#grep exec_EZ src/*.c
#grep exec_E_pct src/*.c
#grep exec_E_ubar src/*.c
grep exec_FB src/*.c
grep exec_FC src/*.c
grep exec_FD src/*.c
grep exec_FK src/*.c
grep exec_FN src/*.c
grep exec_FR src/*.c
grep exec_FS src/*.c
grep exec_F_apos src/*.c
grep exec_F_langle src/*.c
grep exec_F_rangle src/*.c
grep exec_F_ubar src/*.c
grep exec_F_vbar src/*.c
grep print_cmd src/*.c
grep scan_A src/*.c
grep scan_B src/*.c
grep scan_bad src/*.c
grep scan_bslash src/*.c
grep scan_comma src/*.c
grep scan_ctrl_b src/*.c
grep scan_ctrl_e src/*.c
grep scan_ctrl_f src/*.c
grep scan_ctrl_h src/*.c
grep scan_ctrl_n src/*.c
grep scan_ctrl_r src/*.c
grep scan_ctrl_s src/*.c
grep scan_ctrl_t src/*.c
grep scan_ctrl_u src/*.c
grep scan_ctrl_ubar src/*.c
grep scan_ctrl_x src/*.c
grep scan_ctrl_y src/*.c
grep scan_ctrl_z src/*.c
grep scan_digits src/*.c
grep scan_dot src/*.c
grep scan_EC src/*.c
grep scan_ED src/*.c
grep scan_EE src/*.c
grep scan_EH src/*.c
grep scan_EJ src/*.c
grep scan_EO src/*.c
grep scan_ES src/*.c
grep scan_ET src/*.c
grep scan_EU src/*.c
grep scan_EV src/*.c
grep scan_EZ src/*.c
grep scan_H src/*.c
grep scan_mod src/*.c
grep scan_operator src/*.c
grep scan_pct src/*.c
grep scan_Q src/*.c
grep scan_quote src/*.c
grep scan_rparen src/*.c
grep scan_tail src/*.c
grep scan_var src/*.c
grep scan_Z src/*.c
