#!/bin/sh
make a_cmd.lob
make bang_cmd.lob
make buffer.lob
make cmd_exec.lob
make cmd_scan.lob
make comma_cmd.lob
make ctrl_a_cmd.lob
make ctrl_b_cmd.lob
make ctrl_d_cmd.lob
make ctrl_e_cmd.lob
make ctrl_f_cmd.lob
make ctrl_h_cmd.lob
make ctrl_i_cmd.lob
make ctrl_o_cmd.lob
make ctrl_r_cmd.lob
make ctrl_t_cmd.lob
make ctrl_u_cmd.lob
make ctrl_x_cmd.lob
make ctrl_z_cmd.lob
make digit_cmd.lob
make ea_cmd.lob
make eb_cmd.lob
make ec_cmd.lob
make e_cmd.lob
make ed_cmd.lob
make ee_cmd.lob
make ef_cmd.lob
make eg_cmd.lob
make eh_cmd.lob
make ei_cmd.lob
make ej_cmd.lob
make ek_cmd.lob
make el_cmd.lob
make em_cmd.lob
make en_cmd.lob
make env_sys.lob
make eo_cmd.lob
make ep_cmd.lob
make e_pct_cmd.lob
make eq_cmd.lob
make equals_cmd.lob
make er_cmd.lob
make errors.lob
make es_cmd.lob
make et_cmd.lob
make e_ubar_cmd.lob
make eu_cmd.lob
make ev_cmd.lob
make ew_cmd.lob
make ex_cmd.lob
make ey_cmd.lob
make ez_cmd.lob
make fc_cmd.lob
make f_cmd.lob
make fd_cmd.lob
make file.lob
make file_sys.lob
make fk_cmd.lob
make fn_cmd.lob
make fr_cmd.lob
make fs_cmd.lob
make f_ubar_cmd.lob
make g_cmd.lob
make get_flag.lob
make i_cmd.lob
make lbracket_cmd.lob
make n_cmd.lob
make o_cmd.lob
make p_cmd.lob
make percent_cmd.lob
#make push_expr.lob
make q_cmd.lob
make qreg.lob
make quote_cmd.lob
make rbracket_cmd.lob
make rparen_cmd.lob
make s_cmd.lob
make stubs.lob
make teco.lob
make term_in.lob
make term_out.lob
make term_sys.lob
make u_cmd.lob
make x_cmd.lob
make y_cmd.lob
