///
///  @file       options.h
///
///  @brief      Header file for teco utility.
///
///  *** This file is automatically generated. DO NOT MODIFY. ***
///
///  @brief      External resources:
///
///  <a href="options.html">List of Command-line options</a>
///
///  @brief      Process command-line options for TECO editor.
///
///  @copyright 2019-2023 Franklin P. Johnston / Nowwith Treble Software
///
///  Permission is hereby granted, free of charge, to any person obtaining a
///  copy of this software and associated documentation files (the "Software"),
///  to deal in the Software without restriction, including without limitation
///  the rights to use, copy, modify, merge, publish, distribute, sublicense,
///  and/or sell copies of the Software, and to permit persons to whom the
///  Software is furnished to do so, subject to the following conditions:
///
///  The above copyright notice and this permission notice shall be included in
///  all copies or substantial portions of the Software.
///
///  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
///  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
///  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
///  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIA-
///  BILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
///  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
///  THE SOFTWARE.
///
////////////////////////////////////////////////////////////////////////////////


///  @brief  Help text string.

static const char * const help_text[] =
{
    "Usage: teco [options] [file]...",
    "",
    "TECO (Text Editor and Corrector) is a character-oriented text",
    "editing language for reading and writing ASCII text files.",
    "",
    "Examples:",
    "",
    "  teco abc               Open 'abc' for input and output.",
    "  teco -R abc            Open 'abc' for input only.",
    "  teco abc xyz           Open 'abc' for input and 'xyz' for output.",
    "  teco abc -O xyz        Equivalent to 'teco abc xyz'",
    "  teco -E abc            Execute the file 'abc' as a TECO macro.",
    "",
    "Environment variables:",
    "",
    "  TECO_INIT              Default initialization file, executed at startup.",
    "  TECO_LIBRARY           Directory of library for TECO macros.",
    "  TECO_MEMORY            File that contains name of last file edited.",
    "  TECO_VTEDIT            Default file for initialization of display mode.",
    "",
    "Text file options:",
    "",
    "  -C, --create           Create new file if file does not exist.",
    "  -c, --nocreate         Do not create new file if file does not exist.",
    "  -F, --formfeed         Enables FF as a page delimiter.",
    "  -f, --noformfeed       Disables FF as a page delimiter.",
    "  -R, --read-only        Open file for input only.",
    "  -r, --noread-only      Open file for input and output.",
    "",
    "Indirect command file options:",
    "",
    "  -A, --arguments        Specify n or m,n arguments for command file.",
    "  -E, --execute=xyz      Execute TECO macro in file 'xyz'.",
    "  -T, --text=xyz         Store text 'xyz' in edit buffer.",
    "",
    "Initialization options:",
    "",
    "  -I, --initialize=xyz   Use initialization file 'xyz' at startup.",
    "  -i, --noinitialize     Ignore TECO_INIT environment variable.",
    "  -m, --nomemory         Ignore TECO_MEMORY environment variable.",
    "",
    "Display options:",
    "",
    "  -D, --display          Enable display mode.",
    "  -S, --scroll=n         Use 'n' lines for scrolling region (implies -D).",
    "  -V, --vtedit=xyz       Use macro in file 'xyz' to initialize display.",
    "  -v, --novtedit         Ignore TECO_VTEDIT environment variable.",
    "",
    "Miscellaneous options:",
    "",
    "  -H, --help             Print this help message.",
    "  -L, --log=xyz          Saves input and output in log file 'xyz'.",
    "  -n, --nodefaults       Equivalent to --noinitialize -nomemory --novtedit).",
    "  -X, --exit             Exit from TECO after executing all command-line options.",
    NULL
};

///  @enum     option_t
///  case values for command-line options.

enum option_t
{
    OPT_A       = 'A',
    OPT_C       = 'C',
    OPT_D       = 'D',
    OPT_E       = 'E',
    OPT_F       = 'F',
    OPT_H       = 'H',
    OPT_I       = 'I',
    OPT_L       = 'L',
    OPT_R       = 'R',
    OPT_S       = 'S',
    OPT_T       = 'T',
    OPT_V       = 'V',
    OPT_X       = 'X',
    OPT_c       = 'c',
    OPT_f       = 'f',
    OPT_i       = 'i',
    OPT_m       = 'm',
    OPT_n       = 'n',
    OPT_r       = 'r',
    OPT_v       = 'v',
    OPT_version = 1,
    OPT_mung
};

///  @var optstring
///  String of short options parsed by getopt_long().

static const char * const optstring = ":A:CDE:FHI:L:RS:T:V:Xcfimnrv";

///  @var    long_options[]
///  @brief  Table of command-line options parsed by getopt_long().

static const struct option long_options[] =
{
    { "arguments",      required_argument,  NULL,  OPT_A       },
    { "create",         no_argument,        NULL,  OPT_C       },
    { "display",        no_argument,        NULL,  OPT_D       },
    { "execute",        required_argument,  NULL,  OPT_E       },
    { "formfeed",       no_argument,        NULL,  OPT_F       },
    { "help",           no_argument,        NULL,  OPT_H       },
    { "initialize",     required_argument,  NULL,  OPT_I       },
    { "log",            required_argument,  NULL,  OPT_L       },
    { "read-only",      no_argument,        NULL,  OPT_R       },
    { "scroll",         required_argument,  NULL,  OPT_S       },
    { "text",           required_argument,  NULL,  OPT_T       },
    { "vtedit",         required_argument,  NULL,  OPT_V       },
    { "exit",           no_argument,        NULL,  OPT_X       },
    { "nocreate",       no_argument,        NULL,  OPT_c       },
    { "noformfeed",     no_argument,        NULL,  OPT_f       },
    { "noinitialize",   no_argument,        NULL,  OPT_i       },
    { "nomemory",       no_argument,        NULL,  OPT_m       },
    { "nodefaults",     no_argument,        NULL,  OPT_n       },
    { "noread-only",    no_argument,        NULL,  OPT_r       },
    { "novtedit",       no_argument,        NULL,  OPT_v       },
    { "version",        no_argument,        NULL,  OPT_version },  // --version option (hidden)
    { "mung",           no_argument,        NULL,  OPT_mung    },  // --mung option (hidden)
    { NULL,             no_argument,        NULL,  0           },  // Markers for end of list
};

