#!/bin/sh
mv 10EDIT.TEC 10edit.tec
mv ADDIDEN1X.TEC addiden1x.tec
mv ADDIDENT1.TEC addident1.tec
mv ADDIDENT.TEC addident.tec
mv ADDIDENTX.TEC addidentx.tec
mv APOLOGY.TEC apology.tec
mv AREALOGIN.TEC arealogin.tec
mv ASORT.TEC asort.tec
mv BLISSCOM.TEC blisscom.tec
mv CAPITALIZE.TEC capitalize.tec
mv CCLIST.TEC cclist.tec
mv CLEANDIFFS.TEC cleandiffs.tec
mv COPYRI.TEC copyri.tec
mv COUNT_CODE_LOG.TEC count_code_log.tec
mv COUNT_CODE.TEC count_code.tec
mv COUNT_CODE_V2.TEC count_code_v2.tec
mv COUNT_CODE_V4.TEC count_code_v4.tec
mv CREATEDIR.TEC createdir.tec
mv DATE.TEC date.tec
mv DEFBLISS.TEC defbliss.tec
mv DEFMARS.TEC defmars.tec
mv DEVMAR.TEC devmar.tec
mv DEV.TEC dev.tec
mv DIGTOS20.TEC digtos20.tec
mv DISKRAT.TEC diskrat.tec
mv DO-EXPIRED.TEC do-expired.tec
mv DOMAR.TEC domar.tec
mv EDITHELP.TEC edithelp.tec
mv EDIT.TEC edit.tec
mv EDMAR.TEC edmar.tec
mv ED.TEC ed.tec
mv ENTRYS.TEC entrys.tec
mv EXPANDLIST.TEC expandlist.tec
mv FINDUNTERM.TEC findunterm.tec
mv FIXIDENT.TEC fixident.tec
mv FIXMAR.TEC fixmar.tec
mv FIXPATCH.TEC fixpatch.tec
mv FLAGC.TEC flagc.tec
mv FLAME.TEC flame.tec
mv FTNCTL.TEC ftnctl.tec
mv GENUPDATE.TEC genupdate.tec
mv HEXDEC.TEC hexdec.tec
mv INDENT.TEC indent.tec
mv IQUOTE.TEC iquote.tec
mv JUSTIFY.TEC justify.tec
mv LINECOUNT.TEC linecount.tec
mv LINENUMBER.TEC linenumber.tec
mv LISTHDR.TEC listhdr.tec
mv LISTMAIL.TEC listmail.tec
mv LISTSLIDES.TEC listslides.tec
mv LISTTEC.TEC listtec.tec
mv LOCAL.TEC local.tec
mv LOWERS.TEC lowers.tec
mv MAKCAP.TEC makcap.tec
mv MAKEDIFF.TEC makediff.tec
mv NEWAUDIT.TEC newaudit.tec
mv NEWMEMO.TEC newmemo.tec
mv NEWREV.TEC newrev.tec
mv NEWSPEC.TEC newspec.tec
mv NODUPS.TEC nodups.tec
mv NULL.TEC null.tec
mv ORDER.TEC order.tec
mv OVERTYPE.TEC overtype.tec
mv PI.TEC pi.tec
mv PRINTHDR.TEC printhdr.tec
mv QUOTE-RPT.TEC quote-rpt.tec
mv QUOTE.TEC quote.tec
mv REPLYLIST.TEC replylist.tec
mv RESET.TEC reset.tec
mv REVERSEDUMP.TEC reversedump.tec
mv RNOCASE.TEC rnocase.tec
mv R.TEC r.tec
mv SDLFILL.TEC sdlfill.tec
mv SEARCH.TEC search.tec
mv SEQUENCE.TEC sequence.tec
mv SMINDENT.TEC smindent.tec
mv SMTP.TEC smtp.tec
mv SORT.TEC sort.tec
mv SPACETAB.TEC spacetab.tec
mv SPLITLINE.TEC splitline.tec
mv STRIP.TEC strip.tec
mv TABSCAPE1.TEC tabscape1.tec
mv TABSPACE1.TEC tabspace1.tec
mv TABSPACE.TEC tabspace.tec
mv TIME.TEC time.tec
mv TXTWPS.TEC txtwps.tec
mv UNDENT.TEC undent.tec
mv UNIQUELOGIN.TEC uniquelogin.tec
mv UNQUOTE1.TEC unquote1.tec
mv UNQUOTE2.TEC unquote2.tec
mv UNQUOTEA.TEC unquotea.tec
mv UNQUOTE.TEC unquote.tec
mv VERSION.TEC version.tec
